parameters:
- name: ManagedVariable
  type: string
  default: ''
- name: valueCounter
  type: string
  default: ''
 
jobs:
- job: GetTheJobDone
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
  - task: CmdLine@2
    displayName: Extra command line
    env:
      envVar: $(ManagedVariable)-$(valueCounter)
      inputs:
      script: |
        echo variable value is:
        echo %envVar%
        echo expression value is:
        echo $(valueCounter)
        echo ##vso[task.setvariable variable=varFromTask;isoutput=true]taskValue
      name: setVar
  - script: |
          echo varFromTask = $(setVar.varFromTask)
- job: GetVariable
  dependsOn: GetTheJobDone
  condition: always()
  variables:
      varFromTask: $[ dependencies.GetTheJobDone.outputs['setVar.varFromTask'] ]
  steps:
  - script: |
         echo varFromTask = $(varFromTask)